### ISSUE TITLE
[help wanted] Unable to run build.bat successfully

### ISSUE THREAD

**Issue by RaineGit** [MNVolkov/Template#3]
I have downloaded the template from this repository and libbip, then I tried to run the build.bat file that's inside the template but this is what I got:
![image](https://user-images.githubusercontent.com/25404214/96881383-81bcc900-147e-11eb-8e3c-dfed05ba722a.png)

I have also tried the same with the English version ([https://myamazfit.ru/attachments/template_app_en-zip.22934/](https://myamazfit.ru/attachments/template_app_en-zip.22934/)) and this is what I got:
![image](https://user-images.githubusercontent.com/25404214/96881595-ba5ca280-147e-11eb-9cb6-49f0366cf0e9.png)

**Comment by MNVolkov** [comment]
Hello, try using previous version toolchain. I use gcc-arm-none-eabi-8-2019-q3-update-win32-sha2.exe22.10.2020, 20:54, "Mcleocito" <notifications@github.com>:
I have downloaded the template from this repository and libbip, then I tried to run the build.bat file inside the template but this is what I get:

I have also tried the same with the English version (https://myamazfit.ru/attachments/template_app_en-zip.22934/) and this is what I got:

**Comment by RaineGit** [comment]
> Hello, try using previous version toolchain. I use gcc-arm-none-eabi-8-2019-q3-update-win32-sha2.exe22.10.2020, 20:54, "Mcleocito" <notifications@github.com>: I have downloaded the template from this repository and libbip, then I tried to run the build.bat file inside the template but this is what I get: I have also tried the same with the English version (https://myamazfit.ru/attachments/template_app_en-zip.22934/) and this is what I got: —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you, it works now!
